import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {

  isAuthenticated: false,
  Users: 
  {
    Username:"",
    FullName:"",
    Password:"",
    Gender:"Nam",
    Latitude:10.54,
    Longitude:20.435,
    avatarLink: null,
    Email:"",
    LastLoginIP:"127.0.0.1"
  }
};


export const accountSlice = createSlice({
  name: 'account',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    doLoginAction: (state,action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.isAuthenticated= true;
      state.Users= action.payload
    },

    doLGetAccountAction: (state,action) => {
        // Redux Toolkit allows us to write "mutating" logic in reducers. It
        // doesn't actually mutate the state because it uses the Immer library,
        // which detects changes to a "draft state" and produces a brand new
        // immutable state based off those changes
        state.isAuthenticated= true
        state.Users= action.payload.Users
    },
    doLogoutAction: (state) => {
      state.isAuthenticated = false;
      state.Users = null;
  },

   
   
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
     
  },
});

export const { doLoginAction,doLGetAccountAction, doLogoutAction } = accountSlice.actions;



export default accountSlice.reducer;
